FROM ubuntu
MAINTAINER Sibi Chakravarthy Ramesh <sibiitdeveloper@gmail.com>

RUN mkdir -p /opt/hackathon

ADD docker-monitor /opt/hackathon/docker-monitor

WORKDIR /opt/hackathon

CMD ["./docker-monitor"]
