apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  creationTimestamp: null
  labels:
    app: CloudConquerors-httpd
  name: CloudConquerors-httpd
  namespace: kube-system
spec:
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: CloudConquerors-httpd
    spec:
      containers:
      - image: httpd:latest
        imagePullPolicy: Always
        name: CloudConquerors-httpd
        resources: {}
status:
  replicas: 0
---
kind: Service
apiVersion: v1
metadata:
  name: httpd
  namespace: kube-system
spec:
  selector:
    app: CloudConquerors-httpd
  ports:
    - protocol: TCP
      name: port2
      port: 8086
      targetPort: 8086
